version: '3.8'

services:
  artemis:
    container_name: artemis
    image: python:3
    #ports:
    #  - "1337:80"
    volumes:
      - ./src:/artemis
    command: echo "Hello World! Art3mis initialized"
