version: '3.8'

services:
  # -----------------------------------
  # Artemis Server, parses, analyses 
  # and creates relations
  # -----------------------------------
  artemis:
    container_name: artemis
    image: python:3.6.9
    links:
      - storage
    #ports:
    #  - "1337:80"
    volumes:
      - ./:/artemis
    command: tail -f /dev/null # Run the server here when it's built


  # -----------------------------------
  # Storage backend for main service
  # -----------------------------------
  storage:
    container_name: storage
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    #volumes:
    #  - ./data:/data/db
