version: '3.8'

services:
  # -----------------------------------
  # Artemis Server, parses, analyses 
  # and creates relations
  # -----------------------------------
  artemis:
    container_name: artemis
    image: python:3
    links:
      - storage
    #ports:
    #  - "1337:80"
    volumes:
      - ./:/artemis
    command: tail -f /dev/null # Run the server here when it's built


  # -----------------------------------
  # Storage backend for main service
  # -----------------------------------
  storage:
    container_name: storage
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    #volumes:
    #  - ./data:/data/db